CREATE TABLE IF NOT EXISTS DebitDetails
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cardHolder VARCHAR(255) NOT NULL,
    sortCode BIGINT NOT NULL,
    accountNumber BIGINT NOT NULL

);

CREATE SEQUENCE debit_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999
CYCLE;