CREATE TABLE IF NOT EXISTS DebitDetails
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cardHolder VARCHAR(255) NOT NULL,
    sortCode BIGINT NOT NULL,
    accountNumber BIGINT NOT NULL

);

