CREATE TABLE IF NOT EXISTS PERIODICALS
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dates VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    genre VARCHAR(255) NOT NULL
);