INSERT INTO USER_BOOKS (USER_ID, BOOK_ID) VALUES (1, 2);
INSERT INTO USER_BOOKS (USER_ID, BOOK_ID) VALUES (1, 37);
INSERT INTO USER_BOOKS (USER_ID, BOOK_ID) VALUES (6, 37);
INSERT INTO USER_BOOKS (USER_ID, BOOK_ID) VALUES (6, 56);